#             _____ 
#       /\   |_   _|
#      /  \    | |  
#     / /\ \   | |  
#    / ____ \ _| |_ 
#   /_/    \_\_____|
#                   
# Made by the BukkitAI team!
# view documentation in example.yml

# Should we print debug lines?
debug: false
# similarity decimal to a bad word for another word to be detected as bad
# ranging from 0% to 100%
similarity: 75.0
# These people are exempt from the cursing rules.
whitelist:
  - ServerAdministratorGuy123

# The main color for commands. 
color1: 3
# The sub color for commands.  
color2: a
