#             _____ 
#       /\   |_   _|
#      /  \    | |  
#     / /\ \   | |  
#    / ____ \ _| |_ 
#   /_/    \_\_____|
#                   
# Made by the BukkitAI team!
name: AdvancedSwearDetection
version: ${project.version}
description: AI designed to automatically learn filter bypasses and block them in the future.
author: BukkitAI Team
# Not to be a jerk; but Walshy really needs to do something.
authors: ['bwfcwalshy', 'ArsenArsen', 'TheEnderCrafter9']
main: org.bukkitai.advancedsweardetection.ASD
commands:
  advancedsweardetection:
    aliases: [asd]
    usage: /asd
permissions:
    AI.*:
        description: Gives access to all ASD features.
        children:
            ASD.data: false
            ASD.moderation: false
            ASD.test: false
            ASD.perm: false
            ASD.color: false
            ASD.load: false
  
