#             _____ 
#       /\   |_   _|
#      /  \    | |  
#     / /\ \   | |  
#    / ____ \ _| |_ 
#   /_/    \_\_____|
#                   
# Made by the BukkitAI team!
name: AdvancedSwearDetection
version: 0.0.1-ALPHA
description: AI designed to automatically learn filter bypasses and block them in the future.
author: BukkitAI Team
authors: ['bwfcwalshy', 'ArsenArsen', 'TheEnderCrafter9', 'I Al Istannen']
main: org.bukkitai.advancedsweardetection.Main
commands:
  advancedsweardetection:
    aliases: [asd]
    usage: /asd
